sudo: false
language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.2
  - DJANGO=3.0

exclude:
  # Python/Django combinations that aren't officially supported
  - { env: DJANGO=1.11, python: "3.7" }
  - { env: DJANGO=3.0, python: "3.5" }

matrix:
  allow_failures:
    - env: DJANGO=1.8


install: pip install tox-travis python-coveralls codecov
script: tox -- -v --cov rest_framework_jwt_oauth2 --cov-report term-missing --flake8
after_success:
  - coveralls
  - codecov
